// Generated by generate-dashboard.mjs. Do not edit.
window.CLAUDE_PM_DATA = {
  "schemaVersion": 1,
  "updatedAt": "2026-07-21",
  "project": {
    "name": "overclocked-hiit-trainer",
    "repository": "MattGestic/overclocked-hiit-trainer",
    "authoritativeSources": [
      "docs/requirements.md",
      "docs/architecture.md",
      "docs/test-plan.md",
      "docs/deployment.md",
      "docs/decisions/0001-monorepo-for-shared-ui.md",
      "docs/decisions/0002-vendor-shared-ui-not-monorepo.md",
      "supabase/schema.sql",
      "CONTRIBUTING.md",
      "README.md"
    ]
  },
  "items": [
    {
      "id": "WI-0001",
      "title": "Reconcile the starter framework with the intended repository",
      "type": "chore",
      "status": "done",
      "priority": "high",
      "owner": "unassigned",
      "summary": "Inspect the intended repository and adapt only repository-specific paths, commands, and factual statements.",
      "acceptanceCriteria": [
        "Authoritative repository documents are identified and linked",
        "Existing package scripts and framework scripts are merged without loss",
        "No application runtime behavior is changed",
        "Framework and available application checks are run",
        "All reconciliation changes and unresolved conflicts are reported"
      ],
      "dependencies": [],
      "sourceRefs": [
        "README.md",
        "package.json",
        "docs/requirements.md",
        "docs/architecture.md"
      ],
      "evidence": [
        "Identified MattGestic/overclocked-hiit-trainer as the target repository (bundle name and CLAUDE.md content match; the other in-scope repo, MyActivities, has no package.json or comparable structure)",
        "Merged pm:validate and pm:dashboard into the existing package.json scripts block without touching dependencies or metadata",
        "npm run pm:validate and npm run pm:dashboard both passed",
        "npm run lint, npm test, and npm run build all passed unchanged after adding the framework",
        "git diff reviewed: only .claude-pm/**, CLAUDE.md, and the package.json scripts block changed"
      ],
      "notes": [],
      "createdAt": "2026-07-20",
      "updatedAt": "2026-07-21"
    },
    {
      "id": "WI-0002",
      "title": "Populate the verified initial backlog",
      "type": "planning",
      "status": "done",
      "priority": "medium",
      "owner": "unassigned",
      "summary": "Create outcome-focused work items from authoritative repository sources after reconciliation.",
      "acceptanceCriteria": [
        "Each item is traceable to repository evidence or an explicit user decision",
        "Dependencies and acceptance criteria are recorded",
        "Speculation is labeled as an unknown rather than stated as fact"
      ],
      "dependencies": [
        "WI-0001"
      ],
      "sourceRefs": [
        "docs/architecture.md"
      ],
      "evidence": [
        "Seeded WI-0003..WI-0005 directly from docs/architecture.md's 'Explicitly deferred, flagged for confirmation' list (lines ~160-192); two adjacent items in that same list (cooldown countdown, extended programme metadata) are explicitly declined per docs/requirements.md's out-of-scope list rather than deferred, so they were intentionally not turned into backlog items — see STATUS.md risks"
      ],
      "notes": [
        "This is an initial seed from one documented list, not an exhaustive backlog; further prioritization is a product/user decision, not something inferred here."
      ],
      "createdAt": "2026-07-20",
      "updatedAt": "2026-07-21"
    },
    {
      "id": "WI-0003",
      "title": "Swipe-to-delete / quick-swap on the block/exercise list",
      "type": "feature",
      "status": "ready",
      "priority": "medium",
      "owner": "unassigned",
      "summary": "A touch-gesture swipe/swap-menu component plus a live exercise-substitution data flow. Was blocked on product/design confirmation — the v3 design reference (WI-0006) now includes a working SwipeRow implementation (swipe left = delete, swipe right = quick-swap or open SwapModal), so this is unblocked as part of the v3 ActiveWorkout screen pass.",
      "acceptanceCriteria": [
        "Delivered as part of WI-0012's ActiveWorkout/exercise-row v3 pass, reusing v3's SwipeRow interaction"
      ],
      "dependencies": [
        "WI-0012"
      ],
      "sourceRefs": [
        "docs/architecture.md"
      ],
      "evidence": [],
      "notes": [
        "Confirmation source: v3 design project src/components.jsx (SwipeRow) and src/swap-modal.jsx (SwapModal), 2026-07-21."
      ],
      "createdAt": "2026-07-21",
      "updatedAt": "2026-07-21"
    },
    {
      "id": "WI-0004",
      "title": "Inline mid-run editing and a \"Back\" reverse-timer control",
      "type": "feature",
      "status": "ready",
      "priority": "medium",
      "owner": "unassigned",
      "summary": "Editable reps/weight + \"confirm as actuals\" during ACTIVE/RECOVER, and a reverse-timer control. Was blocked on product/design confirmation and a decision on whether in-run edits should mutate the shared programme object. The v3 reference resolves both: edits go through the same onUpdateProgram path already used elsewhere (no new mutation model), and a Back control already exists in useTimerEngine's action set to extend.",
      "acceptanceCriteria": [
        "Delivered as part of WI-0013's Countdown/TimerRun v3 pass; needs its own timerReducer test coverage per docs/architecture.md, not a rubber-stamp"
      ],
      "dependencies": [
        "WI-0013"
      ],
      "sourceRefs": [
        "docs/architecture.md",
        "src/hooks/useTimerEngine.js"
      ],
      "evidence": [],
      "notes": [
        "Confirmation source: v3 design project src/countdown.jsx (ExerciseCard editable + confirm-as-actuals, setRunning('back')), 2026-07-21."
      ],
      "createdAt": "2026-07-21",
      "updatedAt": "2026-07-21"
    },
    {
      "id": "WI-0005",
      "title": "Per-block \"inherit programme interval\" override + between-blocks recovery interval",
      "type": "feature",
      "status": "ready",
      "priority": "medium",
      "owner": "unassigned",
      "summary": "Needs new blocks/programmes schema columns and new phase-engine behaviour. Was blocked on product/design confirmation — the v3 reference now specifies both the editor UI (per-block \"inherit programme interval\" checkbox + override chips) and the between-blocks concept already partially scaffolded in schema (between_blocks_seconds).",
      "acceptanceCriteria": [
        "Delivered as part of WI-0012/WI-0013; needs new blocks.active_seconds/recover_seconds-override columns and a between-blocks phase in useTimerEngine, not just UI"
      ],
      "dependencies": [
        "WI-0012",
        "WI-0013"
      ],
      "sourceRefs": [
        "docs/architecture.md",
        "supabase/schema.sql"
      ],
      "evidence": [],
      "notes": [
        "Confirmation source: v3 design project src/active.jsx (per-block interval override UI) and src/countdown.jsx (betweenBlocksSec handling), 2026-07-21."
      ],
      "createdAt": "2026-07-21",
      "updatedAt": "2026-07-21"
    },
    {
      "id": "WI-0006",
      "title": "Implement OVERCLOCK Refined UI v3 — screen-by-screen visual refresh",
      "type": "feature",
      "status": "in_progress",
      "priority": "high",
      "owner": "unassigned",
      "summary": "Replicate the v3 design mockup (claude.ai/design project 019e20f9-729f-772a-8791-fac43e006909, file 'OVERCLOCK Refined UI v3.html') across every screen: Library, History, ActiveWorkout/Programme details, Countdown/TimerRun, Quick Select/Swap modal, and Toast. The mockup is a static reference (its own simplified useTimer/advance timer engine, hardcoded WeekDatePicker data, and un-wired buttons in places) — the real app's tested useTimerEngine/timerReducer, Supabase-backed data layer, and existing navigation stay as the source of truth; only the visual/interaction layer is ported. Landed as a sequence of small, always-green commits, one screen/fix at a time, per CONTRIBUTING.md.",
      "acceptanceCriteria": [
        "Each screen visually matches the v3 reference using the app's real data (no hardcoded mock data ported in)",
        "The four reported bugs (Library date-filter, History click-to-open, Toast obstruction, Toast palette) are fixed",
        "npm run lint/test/build pass at every commit, not just the final one",
        "Redundant/superseded code from the pre-v3 implementation is removed, not left dead"
      ],
      "dependencies": [],
      "sourceRefs": [
        "src/components/Library.jsx",
        "src/components/History.jsx",
        "src/components/ActiveWorkout.jsx",
        "src/components/TimerRun.jsx",
        "src/shared-ui/components/Toast.jsx"
      ],
      "evidence": [],
      "notes": [
        "External design reference (not a repo path): https://claude.ai/design/p/019e20f9-729f-772a-8791-fac43e006909?file=OVERCLOCK+Refined+UI+v3.html"
      ],
      "createdAt": "2026-07-21",
      "updatedAt": "2026-07-21"
    },
    {
      "id": "WI-0007",
      "title": "Bug: Library week-summary date selection doesn't filter the programme list",
      "type": "bug",
      "status": "in_progress",
      "priority": "high",
      "owner": "unassigned",
      "summary": "The WeekCalendar day cells on Library have no click handler at all — selecting a day does nothing. Should filter the Programmes list to what was actually run that day, using real session_logs data.",
      "acceptanceCriteria": [
        "Tapping a day filters the Programmes list to sessions logged that day; tapping again (or a clear affordance) resets to the full list"
      ],
      "dependencies": [],
      "sourceRefs": [
        "src/components/Library.jsx",
        "src/lib/sessionLogsApi.js"
      ],
      "evidence": [],
      "notes": [],
      "createdAt": "2026-07-21",
      "updatedAt": "2026-07-21"
    },
    {
      "id": "WI-0008",
      "title": "Bug: History session rows aren't clickable — can't open any activity",
      "type": "bug",
      "status": "done",
      "priority": "high",
      "owner": "unassigned",
      "summary": "Session rows in the Recent Sessions list are plain divs with no onClick. programme_id also isn't selected by listAllSessions(), so there's nothing to navigate to even if a handler existed.",
      "acceptanceCriteria": [
        "Tapping a session with a still-existing programme navigates to it; tapping one whose programme was deleted explains why instead of silently doing nothing"
      ],
      "dependencies": [],
      "sourceRefs": [
        "src/components/History.jsx",
        "src/lib/sessionLogsApi.js"
      ],
      "evidence": [
        "Added programme_id to listAllSessions()'s select — it was previously omitted entirely",
        "Session rows are now real <button> elements; a row with a programme_id navigates to { screen: 'workout', programmeId }, one without (programme was deleted) shows a toast explaining why instead of silently no-oping",
        "npm run lint/test pass"
      ],
      "notes": [],
      "createdAt": "2026-07-21",
      "updatedAt": "2026-07-21"
    },
    {
      "id": "WI-0009",
      "title": "Bug: Toast notifications obstruct buttons/navigation and use an off-palette color scheme",
      "type": "bug",
      "status": "done",
      "priority": "high",
      "owner": "unassigned",
      "summary": "Toast renders top-anchored, full-width, z-index 9999, directly over each screen's header controls (Settings gear, Edit/Start, back button). Its light pink/green banner colors also read as a different visual system from the rest of the app's ink/cream/green language.",
      "acceptanceCriteria": [
        "Toast no longer overlaps interactive controls on any screen",
        "Toast styling reuses existing design tokens already used elsewhere in the app (ink-card treatment), not a new ad hoc palette"
      ],
      "dependencies": [],
      "sourceRefs": [
        "src/shared-ui/components/Toast.jsx"
      ],
      "evidence": [
        "Repositioned to bottom (above the bottom nav) instead of top-anchored full-width; narrower max-width, moderate var(--z-toast) instead of 9999",
        "Restyled to the ink-card treatment already used elsewhere (var(--color-bg-inverse)/--color-text-inverse/--color-border-inverse), with a small status dot (--color-timer-work success / --color-error-icon error) instead of pink/green banner backgrounds",
        "Verified visually with a Playwright screenshot: toast no longer overlaps header EDIT/START buttons, sits cleanly above the tab bar"
      ],
      "notes": [],
      "createdAt": "2026-07-21",
      "updatedAt": "2026-07-21"
    },
    {
      "id": "WI-0010",
      "title": "v3 visual refresh — History screen",
      "type": "feature",
      "status": "backlog",
      "priority": "medium",
      "owner": "unassigned",
      "summary": "Port v3's month-calendar layout, stat tiles, and to-date/forecast/final summary mode styling onto the existing (already largely equivalent) History screen.",
      "acceptanceCriteria": [
        "Unknown — size after WI-0007/0008 land"
      ],
      "dependencies": [
        "WI-0006"
      ],
      "sourceRefs": [],
      "evidence": [],
      "notes": [],
      "createdAt": "2026-07-21",
      "updatedAt": "2026-07-21"
    },
    {
      "id": "WI-0011",
      "title": "v3 visual refresh — ActiveWorkout + Programme details/parameters card",
      "type": "feature",
      "status": "backlog",
      "priority": "medium",
      "owner": "unassigned",
      "summary": "Port v3's ProgramDetails card layout and ActiveWorkout header/block-list styling onto ProgrammeParameters/ActiveWorkout, reconciling with the documented out-of-scope decisions (no cooldown, no extended coach/athlete metadata).",
      "acceptanceCriteria": [
        "Unknown — size after WI-0003/0005 scoping"
      ],
      "dependencies": [
        "WI-0006"
      ],
      "sourceRefs": [],
      "evidence": [],
      "notes": [],
      "createdAt": "2026-07-21",
      "updatedAt": "2026-07-21"
    },
    {
      "id": "WI-0012",
      "title": "v3 visual refresh — ActiveWorkout exercise rows (SwipeRow) + Swap modal",
      "type": "feature",
      "status": "backlog",
      "priority": "medium",
      "owner": "unassigned",
      "summary": "Port v3's SwipeRow (swipe-to-delete / quick-swap / open SwapModal) onto the existing block/exercise list. Delivers WI-0003.",
      "acceptanceCriteria": [
        "Unknown — size before starting"
      ],
      "dependencies": [
        "WI-0006"
      ],
      "sourceRefs": [],
      "evidence": [],
      "notes": [],
      "createdAt": "2026-07-21",
      "updatedAt": "2026-07-21"
    },
    {
      "id": "WI-0013",
      "title": "v3 visual refresh — Countdown/TimerRun (NEXT/THEN tiles, settings flyout, split view)",
      "type": "feature",
      "status": "backlog",
      "priority": "medium",
      "owner": "unassigned",
      "summary": "Port v3's fullscreen countdown layout — NEXT/THEN preview tiles, consolidated settings flyout (saturated/split/volume), inline actuals editing — onto TimerRun, keeping useTimerEngine as the source of truth. Delivers part of WI-0004.",
      "acceptanceCriteria": [
        "Unknown — size before starting; needs timerReducer test coverage for any new actions"
      ],
      "dependencies": [
        "WI-0006"
      ],
      "sourceRefs": [],
      "evidence": [],
      "notes": [],
      "createdAt": "2026-07-21",
      "updatedAt": "2026-07-21"
    }
  ]
};
